### ISSUE TITLE
GCC6 warnings

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1345]
GCC6 warns about things that it didnt warn about before, especially 

`-Wmisleading-indentation` 
  * [x] razers/outputFormat.h [in #1409]
  * [x] razers/razers.cpp [in #1409]
  * [x] razers/razers_matepairs.h [in #1409]
  * [x] consensus_base.h [in #1409]
  * [x] index_dfi.h [in #1409]
  * [x] snp_store.h [in #1412]
  * [x] fiona.cpp [in #1412]
  * ~~seqcons.cpp [only master]~~
  * ~~seqan_flexlib.cpp [only master]~~
  * ~~razers2/* [only master]~~
  * [x] tree_recon.cpp [in #1412]
  * [x] insegt/create_gff.h [in #1412]
  * [x] insegt/overlap_module.h [in #1412]
  * [x] micro_razers/*  [in #1412]
  * [x] splazers/* [in #1412]
  * [x] pool_mapper.h [in #1412]

`-Wmaybe-uninitialized` 
  * only fixed in develop by #1356
  * [x] master fix outstanding

`-Wstrict-aliasing`
  * [x] sequence_file.h  [in #1409]

`-Wshift-negative-value`
  * [x] find_myers_ukkonen.h
  * http://cdash.seqan.de/viewBuildError.php?type=1&buildid=162769

GCC5 on mac only:

`-Warray-bounds`
  * [x] misc/edit_environment.h
  * http://cdash.seqan.de/viewBuildError.php?type=1&onlydeltap&buildid=162782

**Comment by h-2** [comment]
the maybe-uninitialized is also triggered by g++5 on travis:
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=160258

**Comment by h-2** [comment]
`-Wmaybe-uninitialized` already fixed by #1356

**Comment by h-2** [comment]
please also investigate these warnings on gcc5/mac:
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=162389
`warning: array subscript is above array bounds`

**Comment by h-2** [comment]
@rrahn I have problems with the last two, can you have look? Especially the one on Mac I cannot reproduce elsewhere... thanks!

**Comment by h-2** [comment]
@rrahn can you look at the mac warning? [making you ticket owner]

**Comment by rrahn** [comment]
I updated the gcc5 compiler and it now works.
