### ISSUE TITLE
update platform support for 2.4.0

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#2193]
* [x] drop icpc-16 on all platforms due to #2142 breakage and bad c++14 support in general
  * [x] update icpc support after 17 and 18 were added to nightlies, see #2199 
  * [x] drop gcc-4.9 on on mac
  * [x] update MSVC support info after adding VS2017, see also #2200

**Comment by marehr** [comment]
So that means we drop gcc 4.9?

**Comment by rrahn** [comment]
On mac, only

**Comment by marehr** [comment]
😞

**Comment by h-2** [comment]
regarding icpc16 this needs to be changed still:
https://github.com/seqan/seqan/blob/develop/util/cmake/SeqAnBuildSystem.cmake#L551
And the whole WINTEL thing needs testing!!

**Comment by marehr** [comment]
CMake seems to support WINTEL redistribution since half a year

https://github.com/Kitware/CMake/blob/2868019b2f93f2eb50de901d8a58ceb9b5790ae5/Modules/InstallRequiredSystemLibraries.cmake#L62-L90

> And the whole WINTEL thing needs testing!!
We test them nightly, what do you mean?

**Comment by h-2** [comment]
> CMake seems to support WINTEL redistribution since half a year

Looks good, can we make use of that?

> We test them nightly, what do you mean?

We test 16 (which we don't support anymore), we don't test 17 and 18.
